name: merge parent

on:
  pull_request_target:
    types:
      - labeled

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'ready-for/merge-parent')
    runs-on: ubuntu-latest
    steps:

      - name: Test
        env:
          PR: ${{ github.event.pull_request.number }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          echo "Running for PR #${PR}"

          PR_BODY=$(
              curl "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${PR}" \
                      --silent \
                      --fail \
                      --header "Accept: application/vnd.github.v3+json" \
                      --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | \
                  jq --raw-output '.body'
          )
          PARENT_PR=$(echo "${PR_BODY}" | head -n 1 | cut -d' ' -f3 | tr -d '\r')
          PARENT_PR_REPO=$(echo "${PARENT_PR}" | cut -d'#' -f1)
          PARENT_PR_ID=$(echo "${PARENT_PR}" | cut -d'#' -f2)

          if test -z "${PARENT_PR_REPO}"; then
              echo "Warning: Unable to extract repository of parent PR. Assuming no parent PR exists."
              exit 0
          fi
          if test -z "${PARENT_PR_ID}"; then
              echo "Warning: Unable to extract ID of parent PR. Assuming no parent PR exists."
              exit 0
          fi

          echo "Merging ${PARENT_PR_REPO}#${PARENT_PR_ID}"
          echo "  Using URL ${GITHUB_API_URL}/repos/${PARENT_PR_REPO}/pulls/${PARENT_PR_ID}/merge"
          echo "  Using data {\"merge_method\": \"rebase\", \"commit_title\": \"Automated merge after ${GITHUB_REPOSITORY}#${PR}\"}"

          curl "${GITHUB_API_URL}/repos/${PARENT_PR_REPO}/pulls/${PARENT_PR_ID}/merge" \
              --silent \
              --fail \
              --request PUT \
              --header "Accept: application/vnd.github.v3+json" \
              --header "Authorization: Bearer ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}" \
              --data "{\"merge_method\": \"rebase\", \"commit_title\": \"Automated merge after ${GITHUB_REPOSITORY}#${PR}\"}"
