name: Release formula

on:
  pull_request:
    types:
      - closed

jobs:

  build:
    name: Release formula
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR number
        id: get-pr-number
        run: |
          PR=$(echo "${GITHUB_REF}" | cut -d'/' -f3)
          echo "Running for PR #${PR}"
          echo "::set-output name=pr-number::${PR}"

      - name: Check for release label
        id: check-release-label
        run: |
          PR="${{ steps.get-pr-number.outputs.pr-number }}"
          echo "Running for PR #${PR}"

          LABELS=$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}" \
                      --silent \
                      --location | \
                  jq --raw-output '.labels[].name'
          )
          IS_RELEASE_PR=false
          for LABEL in ${LABELS}; do
              if test "${LABEL}" == "ready-for/review"; then
                  IS_RELEASE_PR=true
                  echo "Found label ready-for/review"
                  echo "::set-output name=is-release-pr::${IS_RELEASE_PR}"
                  break
              fi
          done

      - name: Create bottle
        id: create-bottle
        if: ${{ steps.check-renovate-label.outputs.is-release-pr }} == "true"
        run: |
          PR="${{ steps.get-pr-number.outputs.pr-number }}"
          echo "Running for PR #${PR}"

          FILES=$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/files" \
                      --silent \
                      --location \
                      --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq --raw-output '.[].filename'
          )
          STARTS_WITH="renovate/"
          for FILE in ${FILES}; do
              if test "${FILE:0:${#STARTS_WITH}}" == "${STARTS_WITH}"; then
                  echo "Updating ${FILE}"
                  bash "${FILE}"
              fi
          done

          ls -l
