name: Update Formula

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  build:
    name: Update Formula
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes
        id: check-for-changes
        run: |
          PR=$(echo "${GITHUB_REF}" | cut -d'/' -f3)
          echo "Running for PR #${PR}"

          LABELS=$(
              curl "https://api.github.com/repos/nicholasdille/homebrew-tap/pulls/11" \
                      --silent \
                      --location | \
                  jq --raw-output '.labels[].name'
          )
          IS_RENOVATE_PR=false
          for LABEL in ${LABELS}; do
              if test "${LABEL}" == "type/renovate"; then
                  IS_RENOVATE_PR=true
                  break
              fi
          done
          if ! ${IS_RENOVATE_PR}; then
              echo "Pull request was not created by renovate"
              exit
          fi

          FILES=$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/files" \
                      --silent \
                      --location \
                      --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq --raw-output '.[].filename'
          )
          echo "Files updated in this PR:"
          STARTS_WITH="renovate/"
          for FILE in ${FILES}; do
              if test "${FILE:0:${#STARTS_WITH}}" == "${STARTS_WITH}"; then
                  bash "${FILE}"
              fi
          done

          git status --short