name: Update formula

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  build:
    name: Update formula
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR number
        id: get-pr-number
        run: |
          PR=$(echo "${GITHUB_REF}" | cut -d'/' -f3)
          echo "Running for PR #${PR}"
          echo "::set-output name=pr-number::${PR}"

      - name: Check for renovate label
        id: check-renovate-label
        run: |
          PR="${{ steps.get-pr-number.outputs.pr-number }}"
          echo "Running for PR #${PR}"

          LABELS=$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}" \
                      --silent \
                      --location | \
                  jq --raw-output '.labels[].name'
          )
          IS_RENOVATE_PR=false
          for LABEL in ${LABELS}; do
              if test "${LABEL}" == "type/renovate"; then
                  IS_RENOVATE_PR=true
                  echo "Found label type/renovate"
                  echo "::set-output name=is-renovate-pr::${IS_RENOVATE_PR}"
                  break
              fi
          done

      - name: Label PR
        id: label-pr
        run: |
          PR="${{ steps.get-pr-number.outputs.pr-number }}"
          echo "Running for PR #${PR}"

          echo "Adding label ready-for/testing"
          curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR}/labels/ready-for/testing" \
              --request "DELETE" \
              --header "Accept: application/vnd.github.v3+json" \
              --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'

      - name: Update formula
        id: update-formula
        if: ${{ steps.check-renovate-label.outputs.is-renovate-pr }} == "true"
        run: |
          PR="${{ steps.get-pr-number.outputs.pr-number }}"
          echo "Running for PR #${PR}"

          FILES=$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/files" \
                      --silent \
                      --location \
                      --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq --raw-output '.[].filename'
          )
          STARTS_WITH="renovate/"
          for FILE in ${FILES}; do
              if test "${FILE:0:${#STARTS_WITH}}" == "${STARTS_WITH}"; then
                  echo "Updating ${FILE}"
                  bash "${FILE}"
              fi
          done

      - name: Commit changes
        id: add-and-commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Formula/*.rb'
          message: 'Updated formulae'

      - name: Label PR
        id: label-pr
        run: |
          PR="${{ steps.get-pr-number.outputs.pr-number }}"
          echo "Running for PR #${PR}"

          echo "Adding label ready-for/testing"
          curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR}/labels" \
              --request "POST" \
              --header "Accept: application/vnd.github.v3+json" \
              --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --data '{ "labels": [ "ready-for/testing" ] }'
